query GetAwayGuidesSlugs {
  awayguides {
  nodes {
      id
      slug
    }
  }
}

query GetAwayGuides($after: String, $limit: Int = 100) {
  awayguides(first: $limit, after: $after, where:  {
     orderby: [ {
        field: DATE,
        order: DESC
     }]
  }) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      title
      awayGuide {
        sport
        division
      }
      slug
    }
  }
}

query GetAwayGuideBySlug($slug: ID!) {
  awayguide(id: $slug, idType: SLUG) {
    id
    title
    date
    awayGuide {
      sport
      division
      farger
      avstand
      hemsida
      matcher
      meriter
      lag
      bildad
      logo {
        sourceUrl
      }
    }
    awayGuideContent {
      text
    }
    slug
  }
}