query GetAwayGames {
  awayGames: awaygames(where: { stati: [PUBLISH, PRIVATE]}) {
    nodes {
      id: databaseId
      status
      awayGame: awaygame {      
        date
        busInfo: businfo
        enemyTeam: enemyteam
        memberPrice: memberprice
        memberPriceYouth: memberpriceYouth
        nonMemberPrice: nonmemberprice
        nonMemberPriceYouth: nonmemberpriceYouth
        buses {
          id
          busName: busname
          maxSeats: maxseats
          requiredSeats: requiredseats
          occupiedSeats: occupiedseats
        }
      }
    }
  }
}