query GetChronicles {
  chronicles {
    nodes {
      id
      date
      chronicle {
        title
        text
      }
      slug
    }
  }
}

query GetChronicle($slug: ID!) {
  chronicle(id: $slug, idType: SLUG) {
    date
    chronicle {
      title
      text
    }
    slug
  }
}