query GetMemberships {
  memberships {
    nodes {
      id
      title
      membershipFields {
        startDate
        endDate
        familyPrice
        regularPrice
        youthPrice
        image {
          node {
            sourceUrl
            altText
          }
        }
        model {
          node {
            id
            mediaItemUrl
          }
        }
      }
    }
  }
}
