query GetNews($limit: Int = 100) {
  newsPosts(first: $limit, where:  {
     orderby: [ {
        field: DATE,
        order: DESC
     }]
  }) {
    nodes {
      id
      date
      newsContent {
        text
        title
        author
        newsImg {
          sourceUrl
          altText
        }
      }
      slug
    }
  }
}

query GetNewsBySlug($slug: ID!) {
  newsPost(id: $slug, idType: SLUG) {
    id
    date
    newsContent {
      text
      title
      author
      newsImg {
        sourceUrl
        altText
      }
    }
    slug
  }
}